namespace emr.Models.Model
{
    public class ObAdmissionsModel
    {
        public int id { get; set; }
        public string? created { get; set; }
        public int creator_id { get; set; }
        public string? modified { get; set; }
        public int modifier_id { get; set; }
        public string? record_date { get; set; }
        public int patient_id { get; set; }
        public bool labor { get; set; }
        public bool induction { get; set; }
        public string? labor_status { get; set; }
        public string? induction_status { get; set; }
        public string? induction_notes { get; set; }
        public bool primarycs { get; set; }
        public string? primarycs_status { get; set; }
        public string? primarycs_notes { get; set; }
        public bool repeatcs { get; set; }
        public bool observation { get; set; }
        public string? repeatcs_status { get; set; }
        public string? observation_status { get; set; }
        public string? observation_notes { get; set; }
        public string? ob_complication { get; set; }
        public bool npc { get; set; }
        public bool pol { get; set; }
        public bool pprom { get; set; }
        public bool cerclage { get; set; }
        public bool pih { get; set; }
        public bool chrhtn { get; set; }
        public bool other { get; set; }
        public string? npc_status { get; set; }
        public string? pol_status { get; set; }
        public string? pprom_status { get; set; }
        public string? cerclage_status { get; set; }
        public string? pih_status { get; set; }
        public string? chrhtn_status { get; set; }
        public string? other_status { get; set; }
        public string? other_notes { get; set; }
        public bool diabetes { get; set; }
        public string? diabetes_status { get; set; }
        public string? diabetes_notes { get; set; }
        public string? diet { get; set; }
        public bool insulin { get; set; }
        public string? insulin_status { get; set; }
        public string? insulin_notes { get; set; }
        public bool amniocentesis { get; set; }
        public string? amniocentesis_status { get; set; }
        public string? amniocentesis_notes { get; set; }
        public string? blood_type { get; set; }
        public string? rhogam { get; set; }
        public string? antibody_screen { get; set; }
        public string? rubella { get; set; }
        public bool chickpox { get; set; }
        public string? chickpox_status { get; set; }
        public string? current_meds { get; set; }
        public string? hepatitis_b { get; set; }
        public string? hiv { get; set; }
        public string? group_b_strep { get; set; }
        public string? gc { get; set; }
        public string? chlamydia { get; set; }
        public string? rpr { get; set; }
        public bool previous_pol { get; set; }
        public bool multi_gestation { get; set; }
        public string? previous_pol_status { get; set; }
        public string? multi_gestation_status { get; set; }
        public string? prev_cs_type { get; set; }
        public string? prev_cs_reason { get; set; }
        public bool previous_pih { get; set; }
        public bool previous_htn { get; set; }
        public bool previous_diabetes { get; set; }
        public string? previous_pih_status { get; set; }
        public string? previous_htn_status { get; set; }
        public string? previous_diabetes_status { get; set; }
        public string? previous_diabetes_notes { get; set; }
        public bool previous_stillbirth { get; set; }
        public bool previous_neodeath { get; set; }
        public bool previous_anomalies { get; set; }
        public bool previous_precipitous { get; set; }
        public bool previous_macrosomia { get; set; }
        public bool previous_pp_hemorrhage { get; set; }
        public bool previous_hx { get; set; }
        public string? previous_stillbirth_status { get; set; }
        public string? previous_neodeath_status { get; set; }
        public string? previous_anomalies_status { get; set; }
        public string? previous_precipitous_status { get; set; }
        public string? previous_macrosomia_status { get; set; }
        public string? previous_pp_hemorrhage_status { get; set; }
        public string? previous_hx_status { get; set; }
        public string? previous_other { get; set; }
        public bool wnl { get; set; }
        public bool nrfs { get; set; }
        public string? wnl_status { get; set; }
        public string? nrfs_status { get; set; }
        public string? fhr { get; set; }
        public string? ltv { get; set; }
        public string? stv { get; set; }
        public bool decreased_fetal_movement { get; set; }
        public bool iugr { get; set; }
        public string? decreased_fetal_movement_status { get; set; }
        public string? iugr_status { get; set; }
        public string? decelerations_notes { get; set; }
        public string? tobacco_use { get; set; }
        public string? tobacco_use_amount { get; set; }
        public string? alcohol_use { get; set; }
        public string? alcohol_use_amount { get; set; }
        public string? drug_use { get; set; }
        public string? drug_use_amount { get; set; }
        public string? primary_language { get; set; }
        public string? other_language { get; set; }
        public bool ongoing_pain { get; set; }
        public bool current_pain { get; set; }
        public string? ongoing_pain_status { get; set; }
        public string? current_pain_status { get; set; }
        public string? creator { get; set; }
        public string? modifier { get; set; }
    }
}
